parameters:
  pool: ''

jobs:
- job: ${{ parameters.pool.os }}_Build
  pool:
    ${{ if eq(parameters.useOneEngineeringPool, 'true') }}:
        ${{ parameters.pool }}
    ${{ else }}:
        vmImage: ${{ parameters.pool.vmImage }}

  displayName: '${{ parameters.pool.emoji }} ${{ parameters.pool.os }} Build and Test'
  templateContext:
    outputs:
    - output: pipelineArtifact
      displayName: '🌐 Publish Install Tool Logs'
      condition: always()
      targetPath: '$(Build.SourcesDirectory)/vscode-dotnet-runtime-extension/dist/test/functional/logs'
      artifactName: '${{ parameters.pool.os }} Install Tool logs-$(currentTimeStamp)'
    - output: pipelineArtifact
      displayName: '👜 Publish SDK Logs'
      condition: always()
      targetPath: '$(Build.SourcesDirectory)/vscode-dotnet-sdk-extension/dist/test/functional/logs'
      artifactName: '${{ parameters.pool.os }} SDK logs-$(currentTimeStamp)'
  steps:
  - template: install-node.yaml
  - pwsh: |
      $date=$(Get-Date -format yyyyMMdd-Hmmss)
      Write-Host "##vso[task.setvariable variable=currentTimeStamp]$date"
    displayName: '🕦 Getting timestamp for unique artifact names'
  - ${{ if eq(parameters.pool.os, 'windows') }}:
    - script: build.cmd
      displayName: 💻 Build Windows
      condition:
    - script: test.cmd
      displayName: 🔍 Test Windows
  - ${{ if eq(parameters.pool.os, 'linux') }}:
    - bash: |
        /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        echo ">>> Started xvfb"
      displayName: 🎮 Start xvfb
  - ${{ if or(eq(parameters.pool.os, 'macOS'), eq(parameters.pool.os, 'linux')) }}:
    - script: ./build.sh
      displayName: 🐧 Build Mac and Linux
      condition:
    - script: ./test.sh
      displayName: 🔎 Test Mac and Linux
      env: {DISPLAY: ':99.0'}
  - ${{ if ne(parameters.useOneEngineeringPool, 'true') }}:
    - task: PublishBuildArtifacts@1
      displayName: ♻️ Publish Public PR Logs
      inputs:
        pathtoPublish: '$(Build.SourcesDirectory)/vscode-dotnet-runtime-extension/dist/test/functional/logs'
        artifactName: 'logs'
      condition: always()
