parameters:
  pool: ''

jobs:
  - job: ESLint
    pool:
      ${{ if eq(parameters.useOneEngineeringPool, 'true') }}:
        ${{ parameters.pool }}
      ${{ else }}:
        vmImage: ${{ parameters.pool.vmImage }}
    displayName: '🧶 ESLint'
    steps:
    - template: install-node.yaml
    - script: build.cmd
    - bash: |
        npm install eslint@^8.57.0 @typescript-eslint/parser@^8.0.0 @typescript-eslint/eslint-plugin@^8.0.0 --reg https://registry.npmjs.org/ --save-dev --verbose
        npm run lint
      displayName: 🧶 Run Lint
