parameters:
  pool: ''

jobs:
- job: ${{ parameters.pool.os }}_Package
  pool:
    ${{ if eq(parameters.useOneEngineeringPool, 'true') }}:
        ${{ parameters.pool }}
    ${{ else }}:
        vmImage: ${{ parameters.pool.vmImage }}
  displayName: '📦 Package and Publish'
  dependsOn:
  - ${{ parameters.pool.os }}_Build
  - TSLint
  condition: succeeded()
  strategy:
    matrix:
      Runtime:
        dir-name: 'vscode-dotnet-runtime-extension'
        package-name: 'vscode-dotnet-runtime'
      SDK:
        dir-name: 'vscode-dotnet-sdk-extension'
        package-name: 'vscode-dotnet-sdk'
  templateContext:
    outputs:
    - output: pipelineArtifact
      displayName: '📂 Publish .VSIX'
      targetPath: '$(Build.ArtifactStagingDirectory)'
      artifactName: '$(dir-name)'
  steps:
  - template: install-node.yaml
  - bash: |
      if ([ $(is-sdk-release) = 'True' ] && [ $(package-name) = 'vscode-dotnet-sdk' ]) || ([ $(is-runtime-release) = 'True' ] && [ $(package-name) = 'vscode-dotnet-runtime' ]); then
        VERSION=`node -p "require('./package.json').version"`
      else
        VERSION_NUM=`node -p "require('./package.json').version"`
        VERSION="$VERSION_NUM-alpha-$(Build.BuildId)"
      fi
      npm version $VERSION --allow-same-version
      echo "##vso[task.setvariable variable=version;isOutput=true]$VERSION"
    name: GetVersion
    displayName: '❓ Get Version'
    workingDirectory: $(dir-name)
  - bash: |
      npm install rimraf --reg https://registry.npmjs.org/ --verbose
      npm install vsce -g --reg https://registry.npmjs.org/ --verbose
      vsce package -o $(package-name)-$(GetVersion.version).vsix --ignoreFile ../.vscodeignore --yarn
    displayName: 📦 Package Artifact
    workingDirectory: $(dir-name)
  - task: CopyFiles@2
    displayName: '📩 Copy Artifact'
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)'
      Contents: '**\*.vsix'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
      flattenFolders: true