parameters:
  pool: ''
  SignType: ''
  version: ''

jobs:
  - job: waitForValidation
    displayName: ☁️ Wait for release approval
    pool: server
    timeoutInMinutes: 4320 # job times out in 3 days
    steps:
    - task: ManualValidation@0
      timeoutInMinutes: 4320
      inputs:
        instructions: 'Please validate that the release build has been tested, and resume to publish a new version'
        onTimeout: 'reject'
  - job: Publish
    pool:
      ${{ if eq(parameters.useOneEngineeringPool, 'true') }}:
        ${{ parameters.pool }}
      ${{ else }}:
        vmImage: ${{ parameters.pool.vmImage }}
    displayName: '🌐 Publish to Marketplace'
    dependsOn:
    - Deploy
    - ${{ parameters.pool.os }}_Package
    variables:
      version: $[ dependencies.GetVersion.outputs['${{ parameters.version }}'] ]
    steps:
    - checkout: none # Skip checking out repo
    - task: DownloadPipelineArtifact@2
      displayName: '⬇️ Download Packaged Extension'
      inputs:
        path: '$(System.ArtifactsDirectory)'
    - template: install-node.yaml
    - task: AzureCLI@2
      displayName: '🚀 Publish to Marketplace'
      inputs:
        azureSubscription: 'VSCode Marketplace Publishing'
        scriptType: "pscore"
        scriptLocation: 'inlineScript'
        workingDirectory: '$(System.ArtifactsDirectory)'
        inlineScript: |
          npm install @vscode/vsce@latest -g --reg https://registry.npmjs.org/ --verbose
          $basePublishArgs = , "publish"
          $basePublishArgs += '--azure-credential'
          $basePublishArgs += '--packagePath'
          $publishArgs = $basePublishArgs + vscode-dotnet-runtime-$(version)-signed.vsix
          If ("${{ parameters.SignType }}" -ne "Real") {
            Write-Host "With a test-signed build, the command to publish is printed instead of run."
            Write-Host "##[command]vsce $publishArgs"
          }
          Else {
            Write-Host "##[command]vsce $publishArgs"
            vsce @publishArgs
          }