parameters:
  pool: ''
  SignType: ''
  useOneEngineeringPool: ''

jobs:
  - job: waitForValidation
    displayName: ☁️ Wait for release approval
    pool: server
    timeoutInMinutes: 4320 # job times out in 3 days
    steps:
    - task: ManualValidation@0
      timeoutInMinutes: 4320
      inputs:
        instructions: 'Please validate that the release build has been tested, and resume to publish a new version'
        onTimeout: 'reject'
  - job: Publish
    pool:
      ${{ parameters.pool }}
    displayName: '🌐 Publish to Marketplace'
    dependsOn:
    - waitForValidation
    - ${{ parameters.pool.os }}_Package
    steps:
    - task: DownloadPipelineArtifact@2
      displayName: '⬇️ Download Packaged Extension'
      inputs:
        path: '$(System.ArtifactsDirectory)'
    - template: install-node.yaml
    - template: list-file-structure.yaml
    - bash: |
        VERSION=`node -p "require('./package.json').version"`
        npm version $VERSION --allow-same-version
        echo "##vso[task.setvariable variable=version;isOutput=true]$VERSION"
      name: GetVersion
      displayName: '❓ Get Version'
      workingDirectory: 'vscode-dotnet-runtime-extension'