parameters:
  pool: ''

jobs:
- job: SBOM
  pool:
    ${{ parameters.pool }}
  displayName: 📝 SBOM Generation
  dependsOn:
  - ${{ parameters.pool.os }}_Build
  - ${{ parameters.pool.os }}_Package
  steps:
    - task: ManifestGeneratorTask@0
      displayName: 📃 SBOM generation
      inputs:
        BuildDropPath: $(System.DefaultWorkingDirectory)
  templateContext:
    outputs:
    - output: pipelineArtifact
      displayName: 📢 Publishing SBOM
      artifact: SBOM
      targetPath: $(System.DefaultWorkingDirectory)/_manifest
    - output: pipelineArtifact
      displayName: 📢 Publishing SBOM for Staging
      artifact: StagedSBOM
      targetPath: '$(Build.ArtifactStagingDirectory)'
