# Name: dotnet.vscode-dotnet-runtime
# URL: https://dev.azure.com/dnceng-public/public/_build?definitionId=60

trigger:
  branches:
    include:
    - main
  tags:
    include:
    - SDK-v*
    - Runtime-v*
pr:
  autoCancel: false
  branches:
    include:
    - '*'

variables:
- name: Codeql.Enabled
  value: true

# The public PR pool schema is different from the 1ES one. We use 'vmImage' which is a default azure pipeline schema. 'os' and 'name' have nothing to do with image selection here.
# 1ES uses 'image' but defining an image this way using our public pools duseOneEngineeringPool not work as they aren't configured this way.
# We can later add the flag 'useOneEngineeringPool' or one engineering system: false or true in all tasks to determine if we use vmImage or a 1es pool object.
parameters:
- name: pools
  type: object
  default:
  - name: NetCore-Public
    vmImage: windows-latest
    os: windows
    emoji: 🪟
  - name: NetCore-Public
    vmImage: ubuntu-latest
    os: linux
    emoji: 🐧
  - name: NetCore-Public
    vmImage: macOS-latest
    os: macOS
    emoji: 🍎

stages:
- stage: o # o is just used so it looks like a bullet point in the output of devops
  jobs:
  - ${{ each image in parameters.pools }}:
    - template: pipeline-templates/build-test.yaml
      parameters:
        pool:
          vmImage: ${{ image.vmImage }}
          os: ${{ image.os }}
          emoji: ${{ image.emoji }}
        useOneEngineeringPool: false
  - template: pipeline-templates/upstream-verify.yaml
    parameters:
      pool:
        vmImage: macOS-latest
        os: macOS
      useOneEngineeringPool: false
  - template: pipeline-templates/lint.yaml
    parameters:
      pool:
        vmImage: macOS-latest
        os: macOS
      useOneEngineeringPool: false
  - template: pipeline-templates/package-vsix.yaml
    parameters:
      pool:
        vmImage: windows-latest
        os: windows
      useOneEngineeringPool: false
      SignType: Test
