name: ðŸž Bug Report
description: Create a report a potential bug
title: Describe the issue you're facing
labels: ["untriaged"]
body:
- type: markdown
  attributes:
    value: |
        Thanks for taking the time to fill out this bug report!
        ðŸ“– Have you checked existing issues to see whether someone else has already reported your issue?
        â— Privacy Alert! The contents in our log files may contain personal data. Prior to posting to GitHub, please remove any personal data which should not be publicly viewable. https://privacy.microsoft.com/en-US/privacystatement"
- type: textarea
  attributes:
    label: Describe the bug. *Please attach log file(s) here if you have any.*
    description: |
      Please share some details about the issue you are facing with the .NET Install Tool.
      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: true
- type: textarea
  attributes:
    label: Please attach log file(s) here if you have any.
    description: |
        Our log files are located alongside VS Code logs. If you want to find them manually, navigate here:
        Linux: ~/.config/Code/logs
        Mac: ~/Library/Application Support/Code/logs/
        Windows: c:\Users\USER\AppData\Roaming\Code\logs\

        Then find the folder created at the time you experienced the bug in the logs folder.
        From there, go to window1 -> exthost -> ms-dotnettools.vscode-dotnet-runtime. The log file should be located in this folder.

        Note: The window folder may change depending on how many VS Code windows you have open; if our extension is running in the 2nd window, it'd be in a folder called window2.
    placeholder: The log file location should be copied to your clipboard if you came from VS Code.
  validations:
    required: true
- type: textarea
  attributes:
    label: Reproduction Steps
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected Behavior
  validations:
    required: true
- type: textarea
  attributes:
    label: Exceptions & Errors (if any)
    description: Errors the extension may have encountered have likely been added to your terminal or VS Code windows. Please paste it/them here and describe what happened and the problem you are facing.
  validations:
    required: false
- type: input
  attributes:
    label: .NET Install Tool Version
    placeholder: e.g. v2.0.0. You can find this by hovering over the extension in VS Code, the version number is to the right of the extension name.
  validations:
    required: true
- type: dropdown
  id: download
  attributes:
    label: Your operating system? Please provide more detail, such as the version and or distro above.
    options:
      - Windows
      - OSX / Darwin / Mac
      - Linux
      - Other
      - N/A
    default: 4
  validations:
    required: true
- type: input
  attributes:
    label: VS Code Version
    placeholder: e.g. 1.84.2. You can find this in VS Code by going to Help -> About -> and finding the Version.
  validations:
    required: false