name: Feature Request
description: Request a new feature for this project
labels: ["feature-request"]
body:
- type: textarea
  attributes:
    label: Is your feature request related to a problem? Please describe.
    placeholder: Example -- I am trying to do [...]. The current feature addresses [...] but does not consider [...].
  validations:
    required: true
- type: textarea
  attributes:
    label: A clear and concise description of what you want to happen. Include any alternative solutions you've considered.
    placeholder: Example -- I would like to have [...] to change from [...] to [...]. The benefit of this is [...].
  validations:
    required: true
- type: textarea
  attributes:
    label: Describe the solution you'd like
  validations:
    required: true
- type: textarea
  attributes:
    label: Additional context
    description: Add any other context or screenshots about the feature request here.
  validations:
    required: false